---
- name: Print path to media archive
  debug:
    msg: "{{ path_to_media_archive }}"

- name: Unarchive backup with media files
  ansible.builtin.unarchive:
    src: "{{ path_to_media_archive }}"
    dest: /home/{{ ansible_user }}/backup/
    remote_src: yes

- name: Remove archive
  ansible.builtin.file:
    state: absent
    path: "{{ path_to_media_archive }}"

- name: Get container Id
  command: "docker ps -qf name=web"
  register: container_id
  tags: 
    - find_container_id

- name: Copy media archive to docker
  become: yes
  ansible.builtin.shell: |
    docker cp /home/{{ ansible_user }}/backup/home {{ container_id.stdout }}:/
  tags:
    - copy_media_to_container

- name: Remove media backup
  ansible.builtin.file:
    state: absent
    path: /home/{{ ansible_user }}/backup/home
# tasks file for push_media
